<a href="https://colab.research.google.com/github/cncs-fit/.github/blob/master/5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [25]:
#練習
def arange_square_matrix(n):
  l = np.zeros((n,n))
  for i in range(n):
    for j in range(n):
      l[i][j] = i+j
  return l

In [26]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))


True


In [27]:
a = np.arange(3)
a[-1]

2

In [ ]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[1:])
print(a[:-2])
print(a[::2])
print(a[::-1])
a[1:4] = 6
print(a)

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]
[0 6 6 6 4]


In [ ]:
a = np.arange(4)
print(a)

print(a + 1) # 各要素に1を加算
print(a - 1) # 各要素に1を減算
print(a * 2) # 各要素に2を乗算
print(a / 2) # 各要素を2で除算
print(a // 2) # 各要素を2で整数除算
print(a % 2) # 各要素に2の剰余演算
print(a ** 2) # 各要素を2乗

print(1 + a) # 左側がスカラでもよい
print(1 - a) # 左側がスカラでもよい
print(2 * a) # 左側がスカラでもよい
b = a + 1
print(1 / b) # 左側がスカラでもよい
print(9 // b) # 左側がスカラでもよい

[0 1 2 3]
[1 2 3 4]
[-1  0  1  2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 0 1]
[0 1 4 9]
[1 2 3 4]
[ 1  0 -1 -2]
[0 2 4 6]
[1.         0.5        0.33333333 0.25      ]
[9 4 3 2]


In [ ]:
a = np.zeros(3) + 2
print(a)
print(np.sqrt(a)) # 各要素はsqrt(2)
b = np.zeros((2,2)) + 2
print(np.sqrt(b)) # 各要素はsqrt(2)
print(np.sqrt(2)) # スカラ（0次元配列）も扱える

[2. 2. 2.]
[1.41421356 1.41421356 1.41421356]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]
1.4142135623730951


In [ ]:
np.dot(np.arange(4), np.arange(1,5)) # 0*1 + 1*2 + 2*3 + 3*4


20

In [ ]:
a = np.array([3, 4, -1, 0, 2])
print(a)
a.sort()
print(a)

[ 3  4 -1  0  2]
[-1  0  2  3  4]


In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.sum())
print(a.sum(0))#列の合計
print(a.sum(1))#行の合計

[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]


In [ ]:
a = np.arange(6)
print(a)
print(a < 3)

[0 1 2 3 4 5]
[ True  True  True False False False]


In [ ]:
a = np.array([0,1,2,-3,-4,5,-6,-7])
print(a)
print(a[a < 0]) # 負の要素を取り出し
print(a[(a < 0) & (a % 2 == 0)]) # 負で偶数の要素を取り出し
a[a < 0] = 8 # 負の要素を8に上書き
print(a)

[ 0  1  2 -3 -4  5 -6 -7]
[-3 -4 -6 -7]
[-4 -6]
[0 1 2 8 8 5 8 8]


In [ ]:
I = np.identity(3)
print(I)
a = np.arange(9).reshape(3,3)
print(a)
print(np.matmul(a, I))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
